package edu.hm.cs.bikebattle.event;

import edu.hm.cs.bikebattle.domain.Drive;
import edu.hm.cs.bikebattle.services.Drive_EventService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.rest.core.event.AbstractRepositoryEventListener;
import org.springframework.stereotype.Component;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */

/**
 * This event-listener allows a DriveEventService to implement logic before and after Events.
 */
@Component
public class Drive_EventListener extends AbstractRepositoryEventListener<Drive> {
	@Autowired
	Drive_EventService service;
	
	@Override
	protected void onAfterCreate(Drive entity) {
		service.onAfterCreate(entity);
	}
	@Override
	protected void onBeforeCreate(Drive entity) {
		service.onBeforeCreate(entity);
	}
	@Override
	protected void onBeforeSave(Drive entity) {
		service.onBeforeSave(entity);
	}
	@Override
	protected void onAfterSave(Drive entity) {
		service.onAfterSave(entity);
	}
	@Override
	protected void onBeforeLinkSave(Drive parent, Object linked) {
		service.onBeforeLinkSave(parent, linked);
	}
	@Override
	protected void onAfterLinkSave(Drive parent, Object linked) {
		service.onAfterLinkSave(parent, linked);
	}
	@Override
	protected void onBeforeLinkDelete(Drive parent, Object linked) {
		service.onBeforeLinkDelete(parent, linked);
	}
	@Override
	protected void onBeforeDelete(Drive entity) {
		service.onBeforeDelete(entity);
	}
	@Override
	protected void onAfterDelete(Drive entity) {
		service.onAfterDelete(entity);
	}
	@Override
	protected void onAfterLinkDelete(Drive parent, Object linked) {
		service.onAfterLinkDelete(parent, linked);
	}
}
